<%@ Page Language="C#" AutoEventWireup="true" CodeFile="ApplicationViewer.aspx.cs" Inherits="ApplicationViewer" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
     <title>Revised Profile</title>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrapcss" />
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


     <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="Mojo - Bootstrap 4 Multipurpose One Page Template" />
    <meta name="author" content="theme_xpress" />
    <link rel="shortcut icon" href="img/favicon.png" />

    <!-- google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Futura:300,400,500,600,700,800,900|Source+Sans+Pro:300,400,600,700,900" rel="stylesheet" />

    <!-- css libraries -->
    <link href="css/bootstrap.min.css" rel="stylesheet" />
    <link href="css/animate.css" rel="stylesheet" />
    <link href="css/font-awesome.min.css" rel="stylesheet" />
    <link href="css/icofont.min.css" rel="stylesheet" />
    <link href="css/owl.carousel.css" rel="stylesheet" />
    <link href="css/lightbox.css" rel="stylesheet" />
    <link href="css/hamburgers.min.css" rel="stylesheet" />

    <!-- main style -->
    <link href="style.css" rel="stylesheet" />
    <!-- responsive.css -->
    <link href="css/responsive.css" rel="stylesheet" />

</head>
<body class="contact1 text-center text-white text-uppercase" style="background: gray;">
     <form id="form1" runat="server">
    <div class="mainheader">
            <header id="mainheader" class="main-header">
                <div class="container">
                    <nav class="navbar navbar-expand-lg main-nav px-0">
                        <a class="navbar-brand" href="#home" rel="m_PageScroll2id">
                            <img src="img/tinylogo.png" alt="Logo" width="400" height="100" />
                        </a>
                        <button class="hamburger hamburger--collapse navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                        </button>
                        <div class="collapse navbar-collapse" id="mainMenu">
                            <ul class="navbar-nav ml-auto text-uppercase f1">
                                <li>
                                    <a href="RevisedLanding.aspx#home" rel="m_PageScroll2id">home</a>
                                </li>
                                <li>
                                    <a href="Application.aspx" rel="m_PageScroll2id" data-ps2id-offset="50">Job Application</a>
                                </li>
                                <li>
                                    <a href="JobSearchPAge.aspx" rel="m_PageScroll2id">Search Jobs</a>
                                </li>

                                <li>
                                    <a href="The Community.aspx" rel="m_PageScroll2id">Create Post</a>
                                </li>

                                <li>
                                    <asp:LinkButton runat="server" ID="logout" OnClick="LogOutUser" rel="m_PageScroll2id">Logout</asp:LinkButton>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
                <!-- /.container -->
            </header>
        </div>
   <br />
         <br />
         <br />

         <br />
          <br />
         <br />

         <br />

     <asp:GridView ID="GridView1"  DataSourceId="MyDataSource"  DataKeyNames="ApplicationID"
        AutoGenerateColumns="false"       AutoGenerateEditButton="false"
        AutoGenerateDeleteButton="false"   runat="server">
    <Columns>
        <asp:BoundField DataField="LastName" HeaderText="LastName"
            SortExpression="LastName" />
        <asp:BoundField DataField="FirstName" HeaderText="FirstName"
            SortExpression="FirstName" />
        <asp:TemplateField  HeaderText="Description">
        <ItemTemplate>
       <%-- <%#Eval("OpportunityName")%>--%>
        </ItemTemplate>
        </asp:TemplateField>
    </Columns>
    </asp:GridView>
        </form>
<asp:SqlDataSource ID="MyDataSource" 
ConnectionString="<%$Connectionstrings:CuedInConnectionString%>"
SelectCommand="SELECT Application.ApplicationID, Application.FirstName as FirstName, Application.LastName as LastName, Application.Email, Opportunity.OpportunityName FROM Application  inner join Opportunity on Opportunity.OpportunityID = Application.OpportunityID" runat="server"></asp:SqlDataSource>
</body>
</html>
